
name: 2.0.0.$(Rev:r)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - modules/XConfigMaster
    

variables:
- group: secrets-base
- group: variables-base
- name: ModulePath
  value: $(System.DefaultWorkingDirectory)/modules/XConfigMaster

jobs:
  - job: publish
    steps:
      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        name: tokenizeModuleDefinition
        displayName: Tokenize Module
        inputs:
          targetFiles: XConfigMaster.psd1
          tokenPrefix: '$('
          tokenSuffix: ')'
          actionOnMissing: fail
          verbosity: detailed
          rootDirectory: $(ModulePath)
      - powershell: Update-ModuleManifest -Path "$(ModulePath)/XConfigMaster.psd1" -FileList (Get-ChildItem "*.*" -Recurse | Foreach-Object {$_.FullName})
        workingDirectory: $(ModulePath)
        name: updateFileList
        displayName: Update Module File List
      - powershell: Publish-Module -NuGetApiKey "$(NuGetApiKey)" -Repository PSGallery -Path $(ModulePath) -Force -Verbose
        name: publishModule
        displayName: Publishing Module 
          
          
    


    
   