
name: 2.0.0.$(Rev:r)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - modules/XConfigMaster
pr: none 

variables:
- template: xpipeline-template-variables.yml

jobs:
  - template: xpipeline-template-base.yml
          
          
    


    
   