
name: $(XConfigMaster.Major).$(XConfigMaster.Minor).$(Rev:r).0

trigger:
  branches:
    include:
    - master
pr: none 

variables:
- template: xpipeline-template-variables.yml

jobs: 
  - template: xpipeline-template-base.yml
          
          
    


    
   