
name: $(XConfigMaster.Major).$(XConfigMaster.Minor).$(Rev:r)-beta

trigger: none
pr:
  branches:
    include:
    - master

variables:
  - template: xpipeline-template-variables.yml
  
jobs:
  - template: xpipeline-template-base.yml
          
    


    
   